# Employee Data Cleaning & Preparation

This notebook performs data inspection, cleaning, missing value handling,
duplicate removal, date transformation, and feature creation for employee data.

In [1]:
# Import Pandas

import pandas as pd

In [2]:
# Dataset Load

df = pd.read_csv("Employee_MIS_Dataset/employees.csv")
df

,Employee_ID,Employee_Name,Gender,Department,Designation,Joining_Date,Location,Salary
0,1001,Karan Singh,Female,HR,HR Manager,2019-01-12,Delhi,33240.0
1,1002,Kavya Soni,Male,IT,System Administrator,2022-03-02,Delhi,114493.0
2,1003,Vikas Agarwal,Female,HR,HR Manager,2019-10-31,Jaipur,93363.0
3,1004,Karan Malhotra,Male,Sales,Business Development Executive,2023-10-30,Panipat,54762.0
4,1005,Varun Jain,Female,Sales,Business Development Executive,2019-02-12,Noida,30259.0
...,...,...,...,...,...,...,...,...
498,1499,Rohan Verma,Male,HR,HR Manager,2025-12-22,Chandigarh,76189.0
499,1500,Meera Bansal,Male,IT,System Administrator,2025-03-31,Gurugram,70511.0
500,1011,Rohan Verma,Male,Sales,Sales Executive,2021-06-09,Noida,85095.0
501,1026,Vivaan Singh,Male,HR,HR Manager,2019-05-21,Delhi,89028.0
502,1101,Amit Mishra,Male,HR,HR Manager,2024-01-01,Delhi,78044.0

In [4]:
# First 5 rows

df.head()

,Employee_ID,Employee_Name,Gender,Department,Designation,Joining_Date,Location,Salary
0,1001,Karan Singh,Female,HR,HR Manager,2019-01-12,Delhi,33240.0
1,1002,Kavya Soni,Male,IT,System Administrator,2022-03-02,Delhi,114493.0
2,1003,Vikas Agarwal,Female,HR,HR Manager,2019-10-31,Jaipur,93363.0
3,1004,Karan Malhotra,Male,Sales,Business Development Executive,2023-10-30,Panipat,54762.0
4,1005,Varun Jain,Female,Sales,Business Development Executive,2019-02-12,Noida,30259.0

In [5]:
# First 10 Rows

df.head(10)

,Employee_ID,Employee_Name,Gender,Department,Designation,Joining_Date,Location,Salary
0,1001,Karan Singh,Female,HR,HR Manager,2019-01-12,Delhi,33240.0
1,1002,Kavya Soni,Male,IT,System Administrator,2022-03-02,Delhi,114493.0
2,1003,Vikas Agarwal,Female,HR,HR Manager,2019-10-31,Jaipur,93363.0
3,1004,Karan Malhotra,Male,Sales,Business Development Executive,2023-10-30,Panipat,54762.0
4,1005,Varun Jain,Female,Sales,Business Development Executive,2019-02-12,Noida,30259.0
5,1006,Ananya Soni,Female,Operations,MIS Executive,2021-08-01,Jaipur,72139.0
6,1007,Arjun Yadav,Female,Marketing,Digital Marketing Analyst,2025-07-18,Jaipur,36849.0
7,1008,Aditya Patel,Male,Marketing,Marketing Executive,2022-09-11,Noida,103768.0
8,1009,Vivaan Yadav,Male,Operations,Operations Executive,2025-12-20,Delhi,111709.0
9,1010,Isha Mishra,Female,Sales,Sales Manager,2025-08-08,Chandigarh,76869.0

In [6]:
# Dataset Size

df.shape

(503, 8)

In [7]:
# Columns Names

df.columns

Index(['Employee_ID', 'Employee_Name', 'Gender', 'Department', 'Designation',
       'Joining_Date', 'Location', 'Salary'],
      dtype='str')

In [8]:
# Dataset Information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    503 non-null    int64
 1   Employee_Name  503 non-null    str
 2   Gender         503 non-null    str
 3   Department     503 non-null    str
 4   Designation    503 non-null    str
 5   Joining_Date   503 non-null    str
 6   Location       495 non-null    str
 7   Salary         498 non-null    float64
dtypes: float64(1), int64(1), str(6)
memory usage: 31.6 KB

In [9]:
# Missing Value Analysis

In [10]:
# Missing Values count

df.isnull().sum()

Employee_ID      0
Employee_Name    0
Gender           0
Department       0
Designation      0
Joining_Date     0
Location         8
Salary           5
dtype: int64

In [11]:
# Missing values percentage

missing_percentage = (df.isnull().sum() / len(df)) * 100
missing_percentage

Employee_ID      0.000000
Employee_Name    0.000000
Gender           0.000000
Department       0.000000
Designation      0.000000
Joining_Date     0.000000
Location         1.590457
Salary           0.994036
dtype: float64

In [12]:
# Only columns having missing values

In [13]:
missing = df.isnull().sum()
missing[missing > 0]

Location    8
Salary      5
dtype: int64

In [15]:
# Rows having any missing value

df[df.isnull().any(axis = 1)]

,Employee_ID,Employee_Name,Gender,Department,Designation,Joining_Date,Location,Salary
31,1032,Nikhil Yadav,Male,Finance,Finance Executive,2021-08-21,NaN,66900.0
47,1048,Karan Mehta,Female,Marketing,Marketing Executive,2025-06-17,NaN,54174.0
67,1068,Rahul Malhotra,Male,Sales,Sales Executive,2021-09-10,NaN,109445.0
129,1130,Neha Sharma,Female,Marketing,Marketing Executive,2023-10-02,Chandigarh,NaN
225,1226,Neha Bansal,Female,Marketing,Digital Marketing Analyst,2021-04-01,Jaipur,NaN
280,1281,Arjun Malhotra,Female,Finance,Accountant,2021-03-30,Panipat,NaN
304,1305,Arjun Kumar,Male,IT,Software Engineer,2021-06-19,NaN,106092.0
310,1311,Ananya Soni,Male,IT,System Administrator,2025-07-13,NaN,49734.0
340,1341,Amit Mehta,Male,Sales,Sales Executive,2020-02-29,NaN,92393.0
384,1385,Aarav Kumar,Male,HR,Recruiter,2023-04-23,Chandigarh,NaN
440,1441,Rahul Verma,Male,Marketing,Digital Marketing Analyst,2019-10-29,Gurugram,NaN
479,1480,Kavya Singh,Female,Sales,Sales Manager,2024-12-16,NaN,88624.0
485,1486,Neha Kumar,Female,Operations,Operations Manager,2023-02-15,NaN,100471.0

In [16]:
# Duplicate Analysis

In [18]:
print(df.duplicated().sum())

3

In [19]:
# Display duplicate rows

df[df.duplicated()]

,Employee_ID,Employee_Name,Gender,Department,Designation,Joining_Date,Location,Salary
500,1011,Rohan Verma,Male,Sales,Sales Executive,2021-06-09,Noida,85095.0
501,1026,Vivaan Singh,Male,HR,HR Manager,2019-05-21,Delhi,89028.0
502,1101,Amit Mishra,Male,HR,HR Manager,2024-01-01,Delhi,78044.0

In [20]:
# Remove duplicates

df = df.drop_duplicates()

In [21]:
# Verify duplicates

df.duplicated().sum()

np.int64(0)

In [22]:
# Category Analysis

In [23]:
# Unique department

df["Department"].unique()

<StringArray>
['HR', 'IT', 'Sales', 'Operations', 'Marketing', 'Finance']
Length: 6, dtype: str

In [24]:
# Department wise count

df["Department"].value_counts()

Department
Sales         91
HR            87
Operations    87
IT            86
Marketing     79
Finance       70
Name: count, dtype: int64

In [26]:
# Location wise count

df["Location"].value_counts(dropna = False)

Location
Panipat       96
Jaipur        91
Gurugram      81
Noida         80
Delhi         73
Chandigarh    71
NaN            8
Name: count, dtype: int64

In [27]:
# Salary Analysis

In [28]:
df["Salary"].describe()

count       495.000000
mean      70867.135354
std       28570.767213
min       22138.000000
25%       44608.500000
50%       71847.000000
75%       96725.000000
max      119938.000000
Name: Salary, dtype: float64

In [30]:
# Salary Median

print(df["Salary"].median())

71847.0

In [31]:
# Store Median

salary_median = df["Salary"].median()

In [32]:
# Fill missing values

df["Salary"] = df["Salary"].fillna(salary_median)

In [33]:
# Check Salary missing values

df["Salary"].isnull().sum()

np.int64(0)

In [34]:
# Location Cleaning

In [35]:
# Fill missing values

df["Location"] = df["Location"].fillna("Unknown")

In [36]:
df["Location"].isnull().sum()

np.int64(0)

In [37]:
# Date Handling

In [40]:
# Check Date Datatype

print(df["Joining_Date"].dtype)

str

In [41]:
# Convert Joining_date to datetime

df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])

In [42]:
# Joining Year

df["Joining_Year"] = df["Joining_Date"].dt.year

In [43]:
# Joining Month

df["Joining_Month"] = df["Joining_Date"].dt.month

In [44]:
# Joining Month Name

df["Joining_Month_Name"] = df["Joining_Date"].dt.month_name()

In [47]:
# Check Date related columns

df[[
    "Joining_Date",
    "Joining_Year",
    "Joining_Month",
    "Joining_Month_Name"
]].head()

  Joining_Date  Joining_Year  Joining_Month Joining_Month_Name
0   2019-01-12          2019              1            January
1   2022-03-02          2022              3              March
2   2019-10-31          2019             10            October
3   2023-10-30          2023             10            October
4   2019-02-12          2019              2           February

In [48]:
# Save cleaned Dataset

df.to_csv("employees_cleaned.csv",index = False)

In [49]:
# Cleaned file reload

pd.read_csv("employees_cleaned.csv").head()

,Employee_ID,Employee_Name,Gender,Department,Designation,Joining_Date,Location,Salary,Joining_Year,Joining_Month,Joining_Month_Name
0,1001,Karan Singh,Female,HR,HR Manager,2019-01-12,Delhi,33240.0,2019,1,January
1,1002,Kavya Soni,Male,IT,System Administrator,2022-03-02,Delhi,114493.0,2022,3,March
2,1003,Vikas Agarwal,Female,HR,HR Manager,2019-10-31,Jaipur,93363.0,2019,10,October
3,1004,Karan Malhotra,Male,Sales,Business Development Executive,2023-10-30,Panipat,54762.0,2023,10,October
4,1005,Varun Jain,Female,Sales,Business Development Executive,2019-02-12,Noida,30259.0,2019,2,February