# Attendance Data Cleaning & Preparation

This notebook performs data inspection, duplicate removal, status standardization,
date transformation, missing value treatment, and working-hours validation.

In [1]:
# Import Pandas

import pandas as pd

In [2]:
# Load Ddfaset

df = pd.read_csv("Employee_MIS_Dataset/attendance.csv")
df

,Attendance_ID,Employee_ID,Date,Status,Working_Hours,Overtime_Hours
0,1,1001,2025-12-26,Present,8.3,1.5
1,2,1001,2025-06-16,Present,8.7,2.2
2,3,1001,2025-10-23,Present,8.5,0.7
3,4,1001,2025-05-27,Present,8.1,0.1
4,5,1001,2025-07-23,Present,8.4,2.2
...,...,...,...,...,...,...
104998,104999,1500,2025-04-30,Present,8.1,1.2
104999,105000,1500,2025-06-30,Leave,0.0,0.0
105000,51,1001,2025-08-07,Present,8.3,1.1
105001,1001,1005,2025-07-03,Present,8.4,1.2
105002,5001,1024,2025-02-05,Present,9.0,1.7

In [3]:
# Ddfa Insepection

In [4]:
# First 5 Rows

df.head()

,Attendance_ID,Employee_ID,Date,Status,Working_Hours,Overtime_Hours
0,1,1001,2025-12-26,Present,8.3,1.5
1,2,1001,2025-06-16,Present,8.7,2.2
2,3,1001,2025-10-23,Present,8.5,0.7
3,4,1001,2025-05-27,Present,8.1,0.1
4,5,1001,2025-07-23,Present,8.4,2.2

In [5]:
# First 10 rows

df.head(10)

,Attendance_ID,Employee_ID,Date,Status,Working_Hours,Overtime_Hours
0,1,1001,2025-12-26,Present,8.3,1.5
1,2,1001,2025-06-16,Present,8.7,2.2
2,3,1001,2025-10-23,Present,8.5,0.7
3,4,1001,2025-05-27,Present,8.1,0.1
4,5,1001,2025-07-23,Present,8.4,2.2
5,6,1001,2025-07-21,Present,8.4,1.8
6,7,1001,2025-09-03,Present,8.7,1.6
7,8,1001,2025-10-03,Present,7.0,3.3
8,9,1001,2025-02-20,Present,7.3,3.0
9,10,1001,2025-05-12,Present,9.3,0.0

In [6]:
# Last 5 rows

df.tail()

,Attendance_ID,Employee_ID,Date,Status,Working_Hours,Overtime_Hours
104998,104999,1500,2025-04-30,Present,8.1,1.2
104999,105000,1500,2025-06-30,Leave,0.0,0.0
105000,51,1001,2025-08-07,Present,8.3,1.1
105001,1001,1005,2025-07-03,Present,8.4,1.2
105002,5001,1024,2025-02-05,Present,9.0,1.7

In [7]:
# Ddfaset size

df.shape

(105003, 6)

In [8]:
# Columns names

df.columns

Index(['Attendance_ID', 'Employee_ID', 'Date', 'Status', 'Working_Hours',
       'Overtime_Hours'],
      dtype='str')

In [9]:
# Data information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 105003 entries, 0 to 105002
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Attendance_ID   105003 non-null  int64
 1   Employee_ID     105003 non-null  int64
 2   Date            105003 non-null  str
 3   Status          105003 non-null  str
 4   Working_Hours   104973 non-null  float64
 5   Overtime_Hours  105003 non-null  float64
dtypes: float64(2), int64(2), str(2)
memory usage: 4.8 MB

In [10]:
# Statistical Summary

df.describe()

       Attendance_ID    Employee_ID  Working_Hours  Overtime_Hours
count  105003.000000  105003.000000  104973.000000   105003.000000
mean    52499.057675    1250.493129       7.093153        0.790060
std     30311.803691     144.341638       2.944739        0.828436
min         1.000000    1001.000000       0.000000        0.000000
25%     26248.500000    1125.000000       7.300000        0.000000
50%     52499.000000    1250.000000       8.000000        0.600000
75%     78749.500000    1375.000000       8.800000        1.400000
max    105000.000000    1500.000000      15.000000        4.800000

In [11]:
# Missing Values

In [12]:
# Missing values count

df.isnull().sum()

Attendance_ID      0
Employee_ID        0
Date               0
Status             0
Working_Hours     30
Overtime_Hours     0
dtype: int64

In [13]:
# Missing Percentage

(df.isnull().sum() / len(df)) * 100

Attendance_ID     0.000000
Employee_ID       0.000000
Date              0.000000
Status            0.000000
Working_Hours     0.028571
Overtime_Hours    0.000000
dtype: float64

In [14]:
# Only coulmns having missing value

missing = df.isnull().sum()
missing[missing > 0]

Working_Hours    30
dtype: int64

In [15]:
# Rows having missing values

df[df.isnull().any(axis = 1)]

,Attendance_ID,Employee_ID,Date,Status,Working_Hours,Overtime_Hours
2286,2287,1011,2025-12-04,Present,NaN,0.0
4068,4069,1020,2025-01-15,Present,NaN,0.0
5105,5106,1025,2025-11-25,Present,NaN,1.1
11738,11739,1056,2025-03-05,Present,NaN,1.3
15713,15714,1075,2025-09-23,Present,NaN,1.6
15792,15793,1076,2025-01-30,Leave,NaN,0.0
19564,19565,1094,2025-08-06,Present,NaN,0.6
23456,23457,1112,2025-02-19,Present,NaN,0.9
24037,24038,1115,2025-12-25,Present,NaN,0.5
27446,27447,1131,2025-06-25,Present,NaN,2.2
31670,31671,1151,2025-10-16,Present,NaN,0.3
36928,36929,1176,2025-01-15,Present,NaN,0.6
39106,39107,1187,2025-12-30,Present,NaN,0.9
41473,41474,1198,2025-02-27,Present,NaN,1.7
43215,43216,1206,2025-09-16,Present,NaN,0.8
45838,45839,1219,2025-07-24,WFH,NaN,2.1
47477,47478,1227,2025-06-16,WFH,NaN,1.5
50484,50485,1241,2025-07-17,Present,NaN,3.3
51028,51029,1243,2025-03-21,Present,NaN,1.3
57977,57978,1277,2025-04-24,Present,NaN,0.2
66844,66845,1319,2025-10-31,Present,NaN,0.0
68988,68989,1329,2025-10-03,Present,NaN,1.2
69223,69224,1330,2025-05-27,Present,NaN,0.6
75918,75919,1362,2025-06-05,WFH,NaN,0.2
77303,77304,1369,2025-06-24,Present,NaN,0.1
80663,80664,1385,2025-09-18,Leave,NaN,0.0
85439,85440,1407,2025-06-16,Present,NaN,0.8
87517,87518,1417,2025-04-17,Present,NaN,0.7
88293,88294,1421,2025-06-24,Present,NaN,1.0
98917,98918,1472,2025-05-27,Present,NaN,1.1

In [16]:
# Duplicates Records

In [17]:
# Count duplicates

print(df.duplicated().sum())

3

In [18]:
# Show Duplicates

df[df.duplicated()]

,Attendance_ID,Employee_ID,Date,Status,Working_Hours,Overtime_Hours
105000,51,1001,2025-08-07,Present,8.3,1.1
105001,1001,1005,2025-07-03,Present,8.4,1.2
105002,5001,1024,2025-02-05,Present,9.0,1.7

In [19]:
# remove duplicates

df = df.drop_duplicates()

In [20]:
print(df.duplicated().sum())

0

In [21]:
# Status analysis

In [22]:
# Unique status value

df["Status"].unique()

<StringArray>
['Present', 'WFH', 'Leave', 'Absent', 'Present ']
Length: 5, dtype: str

In [23]:
# Status Frequency

df["Status"].value_counts(dropna = False)

Status
Present     81793
WFH          8454
Leave        8415
Absent       6323
Present        15
Name: count, dtype: int64

In [24]:
# Remove unwnated spaces

df["Status"] = df["Status"].str.strip()

In [25]:
df["Status"].unique()

<StringArray>
['Present', 'WFH', 'Leave', 'Absent']
Length: 4, dtype: str

In [26]:
df["Status"].value_counts()

Status
Present    81808
WFH         8454
Leave       8415
Absent      6323
Name: count, dtype: int64

In [27]:
# Date Cleaning

In [28]:
# Check Date Datatype

print(df["Date"].dtype)

str

In [29]:
# Convert Date

df["Date"] = pd.to_datetime(df["Date"])

In [30]:
# Verify

print(df["Date"].dtype)

datetime64[us]

In [31]:
# Date Based MIS columns

In [32]:
# Year

df["Year"] = df["Date"].dt.year

In [33]:
# Month Number

df["Month"] = df["Date"].dt.month

In [34]:
# Month name

df["Month_Name"] = df["Date"].dt.month_name()

In [35]:
# Day Name

df["Day_Name"] = df["Date"].dt.day_name()

In [36]:
# Weekday/Weekend

df["Day_Type"] = df["Date"].dt.dayofweek.map(
    lambda x: "Weekend" if x >= 5 else "Weekday"
)

In [37]:
# Working Hours Analysis

In [38]:
# Check missing working hours

print(df["Working_Hours"].isnull().sum())

30

In [39]:
# Working Hours Statistics

df["Working_Hours"].describe()

count    104970.00000
mean          7.09311
std           2.94477
min           0.00000
25%           7.30000
50%           8.00000
75%           8.80000
max          15.00000
Name: Working_Hours, dtype: float64

In [40]:
# Check Unusual working hours

df[df["Working_Hours"] > 12]

,Attendance_ID,Employee_ID,Date,Status,Working_Hours,Overtime_Hours,Year,Month,Month_Name,Day_Name,Day_Type
8707,8708,1042,2025-12-30,Present,15.0,1.8,2025,12,December,Tuesday,Weekday
11221,11222,1054,2025-05-05,Leave,15.0,0.0,2025,5,May,Monday,Weekday
28350,28351,1136,2025-11-11,Present,15.0,0.0,2025,11,November,Tuesday,Weekday
44899,44900,1214,2025-03-17,Present,15.0,0.0,2025,3,March,Monday,Weekday
63971,63972,1305,2025-08-27,Present,15.0,0.1,2025,8,August,Wednesday,Weekday
64549,64550,1308,2025-07-29,Present,15.0,0.0,2025,7,July,Tuesday,Weekday
81281,81282,1388,2025-07-29,Present,15.0,0.2,2025,7,July,Tuesday,Weekday
94622,94623,1451,2025-12-30,Present,15.0,0.2,2025,12,December,Tuesday,Weekday
95204,95205,1454,2025-11-21,WFH,15.0,0.4,2025,11,November,Friday,Weekday
100364,100365,1478,2025-05-27,Present,15.0,0.3,2025,5,May,Tuesday,Weekday

In [41]:
# Wroking Hours Cleaning

In [42]:
# Agar company policy ke according 12 hours se zyada valid nahi hai, to unhe missing mark kar sakte hain

df.loc[df["Working_Hours"] > 12, "Working_Hours"] = pd.NA

In [43]:
df["Working_Hours"].isnull().sum()

np.int64(40)

In [44]:
# Working Hours Fill

In [48]:
df.loc[df["Status"].isin(["Absent","Leave"]),"Working_Hours"] = 0

In [49]:
print(df["Working_Hours"].isnull().sum())

37

In [50]:
# Baaki missing values ko median se fill kar sakte hain

working_hours_median = df["Working_Hours"].median()

In [51]:
df["Working_Hours"] = df["Working_Hours"].fillna(working_hours_median)

In [52]:
print(df["Working_Hours"].isnull().sum())

0

In [53]:
# Overtime Analysis

In [54]:
# Overtime statistics

df["Overtime_Hours"].describe()

count    105000.000000
mean          0.790045
std           0.828441
min           0.000000
25%           0.000000
50%           0.600000
75%           1.400000
max           4.800000
Name: Overtime_Hours, dtype: float64

In [55]:
# Negative Overtime check

df[df["Overtime_Hours"] < 0]

Empty DataFrame
Columns: [Attendance_ID, Employee_ID, Date, Status, Working_Hours, Overtime_Hours, Year, Month, Month_Name, Day_Name, Day_Type]
Index: []

In [56]:
# Missing Overtime

df["Overtime_Hours"].isnull().sum()

np.int64(0)

In [57]:
# Final Data Quality Check

In [58]:
# Missing Values

df.isnull().sum()

Attendance_ID     0
Employee_ID       0
Date              0
Status            0
Working_Hours     0
Overtime_Hours    0
Year              0
Month             0
Month_Name        0
Day_Name          0
Day_Type          0
dtype: int64

In [60]:
# Duplicate Check

print(df.duplicated().sum())

0

In [61]:
# Datatypes

df.dtypes

Attendance_ID              int64
Employee_ID                int64
Date              datetime64[us]
Status                       str
Working_Hours            float64
Overtime_Hours           float64
Year                       int32
Month                      int32
Month_Name                   str
Day_Name                     str
Day_Type                     str
dtype: object

In [62]:
# Final Shape

df.shape

(105000, 11)

In [63]:
# final preview

df.head()

,Attendance_ID,Employee_ID,Date,Status,Working_Hours,Overtime_Hours,Year,Month,Month_Name,Day_Name,Day_Type
0,1,1001,2025-12-26,Present,8.3,1.5,2025,12,December,Friday,Weekday
1,2,1001,2025-06-16,Present,8.7,2.2,2025,6,June,Monday,Weekday
2,3,1001,2025-10-23,Present,8.5,0.7,2025,10,October,Thursday,Weekday
3,4,1001,2025-05-27,Present,8.1,0.1,2025,5,May,Tuesday,Weekday
4,5,1001,2025-07-23,Present,8.4,2.2,2025,7,July,Wednesday,Weekday

# Useful MIS Analysis

In [65]:
# Status wise attendence

df["Status"].value_counts()

Status
Present    81808
WFH         8454
Leave       8415
Absent      6323
Name: count, dtype: int64

In [66]:
# Employee wise attendence

df["Employee_ID"].value_counts()

Employee_ID
1001    210
1002    210
1003    210
1004    210
1005    210
       ...
1496    210
1497    210
1498    210
1499    210
1500    210
Name: count, Length: 500, dtype: int64

In [71]:
# Monthly Attendance

df[df["Status"] == "Present"].groupby(
    ["Year", "Month_Name"]
).size()

Year  Month_Name
2025  April         6964
      August        6653
      December      7198
      February      6274
      January       7269
      July          7204
      June          6570
      March         6512
      May           6895
      November      6206
      October       7164
      September     6899
dtype: int64

In [72]:
# Day Type

df["Day_Type"].value_counts()

Day_Type
Weekday    105000
Name: count, dtype: int64

In [73]:
# Save clean Dataset

df.to_csv(
    "attendance_cleaned.csv",
    index=False
)

In [74]:
pd.read_csv("attendance_cleaned.csv").head()

,Attendance_ID,Employee_ID,Date,Status,Working_Hours,Overtime_Hours,Year,Month,Month_Name,Day_Name,Day_Type
0,1,1001,2025-12-26,Present,8.3,1.5,2025,12,December,Friday,Weekday
1,2,1001,2025-06-16,Present,8.7,2.2,2025,6,June,Monday,Weekday
2,3,1001,2025-10-23,Present,8.5,0.7,2025,10,October,Thursday,Weekday
3,4,1001,2025-05-27,Present,8.1,0.1,2025,5,May,Tuesday,Weekday
4,5,1001,2025-07-23,Present,8.4,2.2,2025,7,July,Wednesday,Weekday